name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: req
      run: apt install libuv1-dev libmosquittopp-dev libmodbus-dev libsqlite3-dev
    - name: make
      run: make
